name: demo

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  demo:
    name: build and release demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build ngx-intersection --configuration production
      - run: yarn build --configuration production --base-href /ngx-intersection/
      - run: |
          git config --global user.name 'Alexander Nickel'
          git config --global user.email 'mr.alexander.nickel@gmail.com'
          git push origin --delete gh-pages
          git add -f dist/ngx-intersection-demo
          git commit -m 'update gh-pages'
          git subtree push --prefix dist/ngx-intersection-demo origin gh-pages
